name: PRODUCTION -CI/CD Pipeline

run-name: PRODUCTION -CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ultralytics

          pip install flake8
          pip install -r requirements.txt
      - name: Testing
        run: echo "Run !"
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ultralytics

          pip install flake8
          pip install -r requirements.txt
      - name: Testing
        run: echo "Run !"
