name: PRODUCTION -CI/CD Pipeline

run-name: PRODUCTION -CI/CD Pipeline


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ultralytics

          pip install flake8
          pip install -r requirements.txt
      - name: Testing
        run: python detect.py --weights runs\train\training\weights\best.pt --img 640 --conf 0.5 --source data/tests
        
      - name: Build Docker Image
        run: |
           docker build -t walidguirat/Industrial_Object_Detection:0.1 .
           docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           docker push walidguirat/Industrial_Object_Detection:0.1
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: vm-83-972@steel-index-259412.iam.gserviceaccount.com
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        run:  gcloud auth activate-service-account --key-file=${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          

      - name: Pull Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull walidguirat/Industrial_Object_Detection:0.1

      - name: Run Docker Container on GCP VM
        run: |
          gcloud compute ssh your-gcp-vm-name --command "docker run -d walidguirat/Industrial_Object_Detection:0.1"


